sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    sprites.destroy(otherSprite, effects.spray, 0)
})
let collectible: Sprite = null
game.splash("Welcome")
tiles.setCurrentTilemap(tilemap`level2`)
info.startCountdown(60)
info.setScore(0)
let mySprite = sprites.create(assets.image`kitty`, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 100)
scene.cameraFollowSprite(mySprite)
game.onUpdateInterval(5000, function () {
    collectible = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ........888.........888.........
        .......811188.....881118........
        .......8aaa118888811aaa8........
        .......8aaaaa81118aaaaa8........
        .......8aaaaa8aaa8aaaaa8........
        .......8aa99989998999aa8........
        ........899999888999998.........
        ........899988989889998.........
        .........8889998999888..........
        .........8999a8.8a9998..........
        ........899aa8...8aa998.........
        .......89aaa8.....8aaa98........
        ........8a88.......88a8.........
        .........8...........8..........
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, SpriteKind.Food)
    collectible.setPosition(randint(0, 160), randint(0, 160))
})
